version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-test:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run

      - run: 
          name: Test blink project 
          command: pip install --upgrade platformio
  
workflows:
  master:
    jobs:
      - build-test
 