version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-test:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install platformio 
          command: pip install --upgrade platformio


      - run:
          name: Install Pyserial 
          command: python -m pip install pyserial

      - run:
          name: Compile project 
          command: pio run 
      - run: 
          name: Header 
          command: cd ~/../../
workflows:
  master:
    jobs:
      - build-test
 