version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run:
          name: Compile Project
          command: pio run
  
  test:
    executor: python/default
    steps::
      -checkout
      - run: 
          name: Install PlatformIO
          command: pip install --upgrade platformio
      - run: 
          name: Test blink 
          command: pio test


workflows:
  master:
    jobs:
      - build
      - test