version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-test:
    executor: python/default
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install requirements.txt
          command: pip install -r requirements.txt
      

      - run: 
          name: Test who iam 
          # command: pio ci --project-conf=platformio.ini src/main.cpp -l "."
          command: whoami
      
      - run: 
          name: Check usb
          command: lsusb

      - run:
          name: Compile Project
          command: pio run
  

workflows:
  master:
    jobs:
      - build-test
 